# Generated by Django 5.0.6 on 2024-06-15 15:28

import core.utils
import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_process', models.BooleanField(default=False, help_text='Kurban videoları arkaplanda düzenli olarak işlensin mi?         İşaretlerseniz, "işlenmemiş" durumundaki videolar otomatik olarak arkaplanda işlenir.', verbose_name='Otomatik İşleme')),
                ('intro', models.FileField(blank=True, help_text='Giriş videosu', null=True, upload_to='intros', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm'])], verbose_name='Giriş')),
                ('outro', models.FileField(blank=True, help_text='Çıkış videosu', null=True, upload_to='outros', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm'])], verbose_name='Çıkış')),
                ('frame', models.ImageField(blank=True, help_text='Çerçeve resmi', null=True, upload_to='frames', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp'])], verbose_name='Çerçeve')),
                ('logo', models.ImageField(blank=True, help_text='Logo resmi', null=True, upload_to='logos', verbose_name='Logo')),
                ('logo_height', models.PositiveIntegerField(default=100, help_text='Logo yüksekliği', verbose_name='Logo Yükseklik')),
                ('logo_position', models.CharField(choices=[('left-top', 'Sol Üst'), ('left-bottom', 'Sol Alt'), ('right-top', 'Sağ Üst'), ('right-bottom', 'Sağ Alt'), ('center', 'Orta')], default='left-top', help_text='Logo pozisyonu', max_length=15, verbose_name='Logo Pozisyon')),
                ('logo_margin_right', models.PositiveSmallIntegerField(default=0, help_text='Logo sağ kenar boşluğu', verbose_name='Logo Sağ Kenar Boşluğu')),
                ('logo_margin_bottom', models.PositiveSmallIntegerField(default=0, help_text='Logo alt kenar boşluğu', verbose_name='Logo Alt Kenar Boşluğu')),
                ('logo_margin_left', models.PositiveSmallIntegerField(default=20, help_text='Logo sol kenar boşluğu', verbose_name='Logo Sol Kenar Boşluğu')),
                ('logo_margin_top', models.PositiveSmallIntegerField(default=20, help_text='Logo üst kenar boşluğu', verbose_name='Logo Üst Kenar Boşluğu')),
                ('name', models.CharField(max_length=127, verbose_name='İsim')),
                ('year', models.PositiveIntegerField(choices=[(1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], default=core.utils.current_year, verbose_name='Yıl')),
            ],
            options={
                'verbose_name': 'Sezon',
                'verbose_name_plural': 'Sezonlar',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Kod/Numara')),
                ('cover', models.ImageField(blank=True, help_text='Kapak resmi', null=True, upload_to='covers', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp'])], verbose_name='Kapak')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'İşlenmemiş'), (2, 'İşleniyor'), (3, 'İşlenmiş'), (4, 'Hata')], default=1, help_text='Video işlenme durumu', verbose_name='Durum')),
                ('original_video', models.FileField(blank=True, help_text='Orijinal kurban kesim videosu', null=True, upload_to=core.utils.animal_video_path_original, verbose_name='Video')),
                ('processed_video', models.FileField(blank=True, help_text='İşlenmiş kurban kesim videosu', null=True, upload_to=core.utils.animal_video_path_processed, verbose_name='İşlenmiş Video')),
                ('season', models.ForeignKey(default=core.utils.current_year, on_delete=django.db.models.deletion.PROTECT, related_name='animals', to='core.season', verbose_name='Sezon')),
            ],
            options={
                'verbose_name': 'Hayvan',
                'verbose_name_plural': 'Hayvanlar',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=127, verbose_name='İsim')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Telefon')),
                ('type', models.PositiveIntegerField(choices=[(1, 'Vacip'), (2, 'Şükür'), (3, 'Akika'), (4, 'Adak')], default=1, verbose_name='Türü')),
                ('by', models.CharField(max_length=127, verbose_name='Vesile')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shares', to='core.animal', verbose_name='Hayvan')),
            ],
            options={
                'verbose_name': 'Hisse',
                'verbose_name_plural': 'Hisseler',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='animal',
            constraint=models.UniqueConstraint(fields=('season', 'code'), name='unique_animal_code_per_season'),
        ),
    ]
