# Generated by Django 5.0.6 on 2024-06-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['-created_at'], 'verbose_name': 'Animal', 'verbose_name_plural': 'Animals'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['-created_at'], 'verbose_name': 'Season', 'verbose_name_plural': 'Seasons'},
        ),
        migrations.AlterModelOptions(
            name='share',
            options={'ordering': ['-created_at'], 'verbose_name': 'Share', 'verbose_name_plural': 'Shares'},
        ),
        migrations.AddField(
            model_name='season',
            name='name',
            field=models.CharField(default='ee', max_length=127),
            preserve_default=False,
        ),
    ]
