# Generated by Django 5.0.6 on 2024-06-15 21:57

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_animal_cover_alter_animal_original_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='processed_video',
            field=models.FileField(blank=True, editable=False, help_text='İşlenmiş kurban kesim videosu', null=True, upload_to=core.utils.animal_video_path_processed, verbose_name='İşlenmiş Video'),
        ),
    ]
