# Generated by Django 5.0.6 on 2024-06-10 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_animal_options_alter_season_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['-created_at'], 'verbose_name': 'Hayvan', 'verbose_name_plural': 'Hayvanlar'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sezon', 'verbose_name_plural': 'Sezonlar'},
        ),
        migrations.AlterModelOptions(
            name='share',
            options={'ordering': ['-created_at'], 'verbose_name': 'Hisse', 'verbose_name_plural': 'Hisseler'},
        ),
    ]
