# Generated by Django 5.0.6 on 2024-06-23 01:29

import core.utils
import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_animal_processed_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='cover',
            field=models.ImageField(blank=True, help_text='Kapak resmi', null=True, upload_to=core.utils.animal_video_path_cover, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp']), core.validators.FileSizeValidator(100)], verbose_name='Kapak'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='original_video',
            field=models.FileField(blank=True, help_text='Orijinal kurban kesim videosu', null=True, upload_to=core.utils.animal_video_path_original, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov']), core.validators.FileSizeValidator(100)], verbose_name='Orjinal Video'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='processed_video',
            field=models.FileField(blank=True, editable=False, help_text='İşlenmiş kurban kesim videosu', null=True, upload_to=core.utils.animal_video_path_processed, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov']), core.validators.FileSizeValidator(100)], verbose_name='İşlenmiş Video'),
        ),
        migrations.AlterField(
            model_name='season',
            name='frame',
            field=models.ImageField(blank=True, help_text='Çerçeve resmi', null=True, upload_to='frames', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp']), core.validators.FileSizeValidator(100)], verbose_name='Çerçeve'),
        ),
        migrations.AlterField(
            model_name='season',
            name='intro',
            field=models.FileField(blank=True, help_text='Giriş videosu', null=True, upload_to='intros', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm']), core.validators.FileSizeValidator(100)], verbose_name='Giriş'),
        ),
        migrations.AlterField(
            model_name='season',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo resmi', null=True, upload_to='logos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp']), core.validators.FileSizeValidator(100)], verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='season',
            name='outro',
            field=models.FileField(blank=True, help_text='Çıkış videosu', null=True, upload_to='outros', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm']), core.validators.FileSizeValidator(100)], verbose_name='Çıkış'),
        ),
    ]
