# Generated by Django 5.0.6 on 2024-06-10 16:55

import core.utils
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_animal_options_alter_season_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Kod/Numara'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='season',
            field=models.ForeignKey(default=core.utils.current_year, on_delete=django.db.models.deletion.PROTECT, related_name='animals', to='core.season', verbose_name='Sezon'),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(max_length=127, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.PositiveIntegerField(choices=[(1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], default=core.utils.current_year, verbose_name='Yıl'),
        ),
        migrations.AlterField(
            model_name='share',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shares', to='core.animal', verbose_name='Hayvan'),
        ),
        migrations.AlterField(
            model_name='share',
            name='by',
            field=models.CharField(max_length=127, verbose_name='Kimin'),
        ),
        migrations.AlterField(
            model_name='share',
            name='name',
            field=models.CharField(max_length=127, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='share',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='share',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Vacip'), (2, 'Şükür'), (3, 'Akika'), (4, 'Adak')], default=1, verbose_name='Türü'),
        ),
    ]
