# Generated by Django 5.0.6 on 2024-06-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_animal_code_alter_animal_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='İşlendi'),
        ),
    ]
