# Generated by Django 5.0.6 on 2024-06-11 03:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_animal_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='frame',
            field=models.ImageField(blank=True, help_text='Çerçeve resmi', null=True, upload_to='frames', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp'])], verbose_name='Çerçeve'),
        ),
        migrations.AddField(
            model_name='season',
            name='intro',
            field=models.FileField(blank=True, help_text='Giriş videosu', null=True, upload_to='intros', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm'])], verbose_name='Giriş'),
        ),
        migrations.AddField(
            model_name='season',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo resmi', null=True, upload_to='logos', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='season',
            name='logo_height',
            field=models.PositiveIntegerField(default=100, help_text='Logo yüksekliği', verbose_name='Logo Yükseklik'),
        ),
        migrations.AddField(
            model_name='season',
            name='logo_margin_bottom',
            field=models.PositiveSmallIntegerField(default=0, help_text='Logo alt kenar boşluğu', verbose_name='Logo Alt Kenar Boşluğu'),
        ),
        migrations.AddField(
            model_name='season',
            name='logo_margin_left',
            field=models.PositiveSmallIntegerField(default=20, help_text='Logo sol kenar boşluğu', verbose_name='Logo Sol Kenar Boşluğu'),
        ),
        migrations.AddField(
            model_name='season',
            name='logo_margin_right',
            field=models.PositiveSmallIntegerField(default=0, help_text='Logo sağ kenar boşluğu', verbose_name='Logo Sağ Kenar Boşluğu'),
        ),
        migrations.AddField(
            model_name='season',
            name='logo_margin_top',
            field=models.PositiveSmallIntegerField(default=20, help_text='Logo üst kenar boşluğu', verbose_name='Logo Üst Kenar Boşluğu'),
        ),
        migrations.AddField(
            model_name='season',
            name='logo_position',
            field=models.CharField(choices=[('left-top', 'Sol Üst'), ('left-bottom', 'Sol Alt'), ('right-top', 'Sağ Üst'), ('right-bottom', 'Sağ Alt'), ('center', 'Orta')], default='left-top', help_text='Logo pozisyonu', max_length=15, verbose_name='Logo Pozisyon'),
        ),
        migrations.AddField(
            model_name='season',
            name='outro',
            field=models.FileField(blank=True, help_text='Çıkış videosu', null=True, upload_to='outros', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm'])], verbose_name='Çıkış'),
        ),
    ]
