# Generated by Django 5.0.6 on 2024-06-11 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_season_frame_season_intro_season_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='cover',
            field=models.ImageField(blank=True, help_text='Kapak resmi', null=True, upload_to='covers', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp'])], verbose_name='Çerçeve'),
        ),
    ]
