# Generated by Django 5.0.6 on 2024-06-11 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_season_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='cover',
        ),
    ]
