# Generated by Django 5.0.6 on 2024-06-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_animal_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='video',
            field=models.FileField(blank=True, editable=False, help_text='Kurban kesim videosu', null=True, upload_to='animals', verbose_name='Video'),
        ),
    ]
