# Generated by Django 5.0.6 on 2024-06-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_animal_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='process',
            field=models.BooleanField(default=False, help_text='Bu sezondaki videolar otomatik oluşturulsun mu?', verbose_name='İşlensin mi?'),
        ),
    ]
