# Generated by Django 5.0.6 on 2024-06-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_season_process'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='processed',
        ),
        migrations.AddField(
            model_name='animal',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'İşlenmemiş'), (2, 'İşleniyor'), (3, 'İşlenmiş'), (4, 'Hata')], default=1, help_text='Video işlenme durumu', verbose_name='Durum'),
        ),
    ]
