# Generated by Django 5.0.6 on 2024-06-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_animal_processed_animal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='by',
            field=models.CharField(max_length=127, verbose_name='Vesile'),
        ),
    ]
