# Generated by Django 5.0.6 on 2024-06-13 08:05

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_share_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Telefon'),
        ),
    ]
