# Generated by Django 5.0.6 on 2024-06-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_share_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='video',
            field=models.FileField(blank=True, help_text='Kurban kesim videosu', null=True, upload_to='animals', verbose_name='Video'),
        ),
    ]
