# Generated by Django 5.0.6 on 2024-06-15 11:11

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_season_logo_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='video',
            field=models.FileField(blank=True, help_text='Kurban kesim videosu', null=True, upload_to=core.models.animal_video_path, verbose_name='Video'),
        ),
    ]
