# Generated by Django 5.0.6 on 2024-06-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_animal_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='process',
        ),
        migrations.AddField(
            model_name='season',
            name='auto_process',
            field=models.BooleanField(default=False, help_text='Kurban videoları arkaplanda düzenli olarak işlensin mi?         İşaretlerseniz, "işlenmemiş" durumundaki videolar otomatik olarak arkaplanda işlenir.', verbose_name='Otomatik İşleme'),
        ),
    ]
